### ISSUE TITLE
error in test

### ISSUE THREAD

**Issue by ghost** [uchida-takumi/CustomizedLinear#2]
Hi I am trying to understand how the masked layer works but i am running into this error:

===================
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-3097c74e2bc9> in <module>
     18         for param in model.parameters():
     19 
---> 20             param -= learning_rate*param.grad
     21             # check masked param.grad
     22             if np.array(param.grad).size == np.array(mask).size:

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Thank you.

**Comment by uchida-takumi** [comment]
Thank for your using CustomizedLinear.
And thanks for teach me this bug.
I can get same error on my PC. I will update this repository to fix this.

please, wait for some days.

**Comment by uchida-takumi** [comment]
> Hi I am trying to understand how the masked layer works but i am running into this error:
> 
> ## ===================
> TypeError Traceback (most recent call last)
> in
> 18 for param in model.parameters():
> 19
> ---> 20 param -= learning_rate*param.grad
> 21 # check masked param.grad
> 22 if np.array(param.grad).size == np.array(mask).size:
> 
> TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> 
> Thank you.

**Comment by uchida-takumi** [comment]
@kengcher 

Now, I updated how_to_use.py.
the important change is adding " if param.requires_grad:" in bellow.

``` python
    # Update the weights
    with torch.no_grad():
        for param in model.parameters():
            # mask is also saved in param, but mask.requires_grad=False
            if param.requires_grad: 
                param -= learning_rate * param.grad
                # check masked param.grad
                if np.array(param.grad).size == np.array(mask).size:
                    print('--- epoch={}, loss={} ---'.format(t,loss.item()))
                    print('↓↓↓masked weight↓↓↓')
                    print(param.t())
                    print('↓↓↓masked grad of weight↓↓↓')
                    print(param.grad.t())
```
mask (that tensor object?) is saved in a param of CustomizedLinear.
but, the saved mask is sete mask.requires_grad=False, so, param.grad=None.
This is because your report.

Thanks for your report very very much.
