### ISSUE TITLE
some questions about register params

### ISSUE THREAD

**Issue by mengyingzhou** [uchida-takumi/CustomizedLinear#3]
hi

thank you for the great work.
I am looking for some ref about the customized networks. I have a question about the annotate written in CustomizedLinear.py
```
when e.g. .cuda() is called. You can use .register_buffer() to register buffers.
```
so, that means  I use some code like this: ```nn.Parameter(Variable(torch.randn(2,3),requires_grad=True)).cuda().register_buffer()```?

but actually it doesn't work.

thank you very much!
Mengying

**Comment by uchida-takumi** [comment]
I'm very sorry that I'm late to reply.
In fact, the comment you have referred is not written by me. 
This is of "https://pytorch.org/docs/stable/notes/extending.html".

I wanted to answer your question, but I have poor knowledge and experience to do that. 
I should not write what I have no...

very very sorry, 
Takumi Uchida
